framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/vendor/xver/micartera-domain/translations'
        fallbacks:
            - '%locale%'
        providers:
